name: rukisha-project-compass
services:
  - name: rukisha-project-compass
    build_command: npm run build
    run_command: npm run start
    http_port: 8080
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: "postgres://username:password@host:port/database"
