name: rukisha-project-compass
static_sites:
  - name: rukisha-project-compass
    build_command: npm run build
    output_dir: dist/client
    catchall_document: index.html
    envs:
      - key: VITE_SUPABASE_URL
        scope: BUILD_TIME
        value: ${VITE_SUPABASE_URL}
      - key: VITE_SUPABASE_PUBLISHABLE_KEY
        scope: BUILD_TIME
        value: ${VITE_SUPABASE_PUBLISHABLE_KEY}
      - key: VITE_SUPABASE_PROJECT_ID
        scope: BUILD_TIME
        value: ${VITE_SUPABASE_PROJECT_ID}
