/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as PProjectIdIndexRouteImport } from './routes/p.$projectId.index'
import { Route as PProjectIdVaultRouteImport } from './routes/p.$projectId.vault'
import { Route as PProjectIdSetupRouteImport } from './routes/p.$projectId.setup'
import { Route as PProjectIdKanbanRouteImport } from './routes/p.$projectId.kanban'
import { Route as PProjectIdDashboardRouteImport } from './routes/p.$projectId.dashboard'
import { Route as PProjectIdCalendarRouteImport } from './routes/p.$projectId.calendar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdIndexRoute = PProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdVaultRoute = PProjectIdVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdSetupRoute = PProjectIdSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdKanbanRoute = PProjectIdKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdDashboardRoute = PProjectIdDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PProjectIdRoute,
} as any)
const PProjectIdCalendarRoute = PProjectIdCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => PProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$projectId': typeof PProjectIdRouteWithChildren
  '/p/$projectId/calendar': typeof PProjectIdCalendarRoute
  '/p/$projectId/dashboard': typeof PProjectIdDashboardRoute
  '/p/$projectId/kanban': typeof PProjectIdKanbanRoute
  '/p/$projectId/setup': typeof PProjectIdSetupRoute
  '/p/$projectId/vault': typeof PProjectIdVaultRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$projectId/calendar': typeof PProjectIdCalendarRoute
  '/p/$projectId/dashboard': typeof PProjectIdDashboardRoute
  '/p/$projectId/kanban': typeof PProjectIdKanbanRoute
  '/p/$projectId/setup': typeof PProjectIdSetupRoute
  '/p/$projectId/vault': typeof PProjectIdVaultRoute
  '/p/$projectId': typeof PProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$projectId': typeof PProjectIdRouteWithChildren
  '/p/$projectId/calendar': typeof PProjectIdCalendarRoute
  '/p/$projectId/dashboard': typeof PProjectIdDashboardRoute
  '/p/$projectId/kanban': typeof PProjectIdKanbanRoute
  '/p/$projectId/setup': typeof PProjectIdSetupRoute
  '/p/$projectId/vault': typeof PProjectIdVaultRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p/$projectId'
    | '/p/$projectId/calendar'
    | '/p/$projectId/dashboard'
    | '/p/$projectId/kanban'
    | '/p/$projectId/setup'
    | '/p/$projectId/vault'
    | '/p/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/p/$projectId/calendar'
    | '/p/$projectId/dashboard'
    | '/p/$projectId/kanban'
    | '/p/$projectId/setup'
    | '/p/$projectId/vault'
    | '/p/$projectId'
  id:
    | '__root__'
    | '/'
    | '/p/$projectId'
    | '/p/$projectId/calendar'
    | '/p/$projectId/dashboard'
    | '/p/$projectId/kanban'
    | '/p/$projectId/setup'
    | '/p/$projectId/vault'
    | '/p/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PProjectIdRoute: typeof PProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/': {
      id: '/p/$projectId/'
      path: '/'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof PProjectIdIndexRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/vault': {
      id: '/p/$projectId/vault'
      path: '/vault'
      fullPath: '/p/$projectId/vault'
      preLoaderRoute: typeof PProjectIdVaultRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/setup': {
      id: '/p/$projectId/setup'
      path: '/setup'
      fullPath: '/p/$projectId/setup'
      preLoaderRoute: typeof PProjectIdSetupRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/kanban': {
      id: '/p/$projectId/kanban'
      path: '/kanban'
      fullPath: '/p/$projectId/kanban'
      preLoaderRoute: typeof PProjectIdKanbanRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/dashboard': {
      id: '/p/$projectId/dashboard'
      path: '/dashboard'
      fullPath: '/p/$projectId/dashboard'
      preLoaderRoute: typeof PProjectIdDashboardRouteImport
      parentRoute: typeof PProjectIdRoute
    }
    '/p/$projectId/calendar': {
      id: '/p/$projectId/calendar'
      path: '/calendar'
      fullPath: '/p/$projectId/calendar'
      preLoaderRoute: typeof PProjectIdCalendarRouteImport
      parentRoute: typeof PProjectIdRoute
    }
  }
}

interface PProjectIdRouteChildren {
  PProjectIdCalendarRoute: typeof PProjectIdCalendarRoute
  PProjectIdDashboardRoute: typeof PProjectIdDashboardRoute
  PProjectIdKanbanRoute: typeof PProjectIdKanbanRoute
  PProjectIdSetupRoute: typeof PProjectIdSetupRoute
  PProjectIdVaultRoute: typeof PProjectIdVaultRoute
  PProjectIdIndexRoute: typeof PProjectIdIndexRoute
}

const PProjectIdRouteChildren: PProjectIdRouteChildren = {
  PProjectIdCalendarRoute: PProjectIdCalendarRoute,
  PProjectIdDashboardRoute: PProjectIdDashboardRoute,
  PProjectIdKanbanRoute: PProjectIdKanbanRoute,
  PProjectIdSetupRoute: PProjectIdSetupRoute,
  PProjectIdVaultRoute: PProjectIdVaultRoute,
  PProjectIdIndexRoute: PProjectIdIndexRoute,
}

const PProjectIdRouteWithChildren = PProjectIdRoute._addFileChildren(
  PProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PProjectIdRoute: PProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
